//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "companies")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub internal_id: Uuid,
    #[sea_orm(unique)]
    pub company_name: String,
    #[sea_orm(unique)]
    pub company_tax_number: String,
    pub company_country: Option<String>,
    pub company_province: Option<String>,
    pub company_postal_code: Option<String>,
    pub company_settlement: Option<String>,
    pub company_street: Option<String>,
    pub company_street_number: Option<String>,
    pub company_email: Option<String>,
    pub company_phone_number: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::company_contacts::Entity")]
    CompanyContacts,
}

impl Related<super::company_contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyContacts.def()
    }
}
