//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "companies")]
#[serde(rename_all = "camelCase")] // we anser with the Model to the Angular FE, and this way it receives camelCase instead of snake_case
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    #[serde(skip_serializing)]  // Skip id when serializing to JSON (--> FE never receives it)
    pub id: i32,
    #[sea_orm(unique)]
    pub internal_id: Uuid,
    #[sea_orm(unique)]
    pub company_name: String,
    #[sea_orm(unique)]
    pub company_tax_number: String,
    pub company_country: Option<String>,
    pub company_province: Option<String>,
    pub company_postal_code: Option<String>,
    pub company_settlement: Option<String>,
    pub company_street: Option<String>,
    pub company_street_number: Option<String>,
    pub company_email: Option<String>,
    pub company_phone_number: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::company_billings::Entity")]
    CompanyBillings,
    #[sea_orm(has_many = "super::company_contacts::Entity")]
    CompanyContacts,
    #[sea_orm(has_many = "super::company_premises::Entity")]
    CompanyPremises,
    #[sea_orm(has_many = "super::workdocuments::Entity")]
    Workdocuments,
}

impl Related<super::company_billings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyBillings.def()
    }
}

impl Related<super::company_contacts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyContacts.def()
    }
}

impl Related<super::company_premises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CompanyPremises.def()
    }
}

impl Related<super::workdocuments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Workdocuments.def()
    }
}
