//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "company_billings")]
#[serde(rename_all = "camelCase")] // we anser with the Model to the Angular FE, and this way it receives camelCase instead of snake_case
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    #[serde(skip_serializing)]  // Skip id when serializing to JSON (--> FE never receives it)
    pub id: i32,
    #[sea_orm(unique)]
    pub internal_id: Uuid,
    #[sea_orm(unique)]
    pub billing_company_name: String,
    #[sea_orm(unique)]
    pub billing_tax_number: String,
    pub billing_email: Option<String>,
    pub billing_country: Option<String>,
    pub billing_province: Option<String>,
    pub billing_postal_code: Option<String>,
    pub billing_settlement: Option<String>,
    pub billing_street: Option<String>,
    pub billing_street_number: Option<String>,
    pub company_iid: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::companies::Entity",
        from = "Column::CompanyIid",
        to = "super::companies::Column::InternalId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Companies,
}

impl Related<super::companies::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Companies.def()
    }
}
