//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod companies;
pub mod company_billings;
pub mod company_contacts;
pub mod company_premises;
pub mod notes;
pub mod pesticides;
pub mod responsible_persons;
pub mod users;
