//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::companies::Entity as Companies;
pub use super::company_contacts::Entity as CompanyContacts;
pub use super::notes::Entity as Notes;
pub use super::users::Entity as Users;
